version: "3"
services:
  web:
    image: spring-boot-monitoring
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 200M
      restart_policy:
        condition: on-failure
    ports:
      - "8081:8081"
    networks:
      - webnet
networks:
  webnet: