server:
  port: 8081
spring:
  security:
    user:
      name: monitor
      password: monitor
  application:
    name: spring-boot-monitoring

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus,info,health